import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import Header from "./(user)/header/header";
import Footer from "./(user)/footer/footer";
import { Providers } from "./providers"; // 👈 dùng wrapper
import { ToastContainer } from "react-toastify";
import { CountProvider } from "./(user)/test/TestUseReducer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vervestyle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${metadata.title}`}
      >
        <Providers>
          {/* <Header /> */}
          <CountProvider>
            {children}
            <ToastContainer
              position="top-right"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
            />
          </CountProvider>

          {/* <Footer /> */}
        </Providers>
      </body>
    </html>
  );
}
