export default interface orderInterface{
    id_don_hang : number,
    ten_nguoi_nhan : string,
    dia_chi_nguoi_nhan : string,
    so_dien_thoai_nguoi_nhan : string,
    ghi_chu_don_hang : string,
    gia_tong_don_hang : number,
    ten_nguoixacnhan : string,
    ten_shipper : string,
    ma_giao_dich : number,
    trang_thai_don_hang : string,
    trang_thai_thanh_toan : string,
    link_thanh_toan : string,
    id_nguoi_xac_nhan : number,
    id_shipper : number,
    id_khach_hang : number,
    id_ma_giam_gia : number,
    id_phuong_thuc_thanh_toan : number,
    kiem_tra_hoan_hang : number,
    created_at : string,
    updated_at : string,
    deleted_at : string,
    tien_ship : number,
}